version: '3'

networks:
  qelog_default:
    external: true

services:
  mongodb:
     image: mongo:4.2
     container_name: qelog_mongo
     volumes:
     # 注意修改挂载路径
      - '/var/lib/mongodb:/data/db'
     environment:
           MONGO_INITDB_ROOT_USERNAME: root
           MONGO_INITDB_ROOT_PASSWORD: 111111
     restart: always

  qelog:
    image: qelog:latest
    container_name: qelog
    ports:
      - '31080:31080'
      - '31082:31082'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/log/qelog:/app/log
      # 注意修改挂载路径
      - ./configs/config.docker.toml:/app/configs/config.toml:ro
    environment:
        SERVER_MODE: single # single | cluster_admin | cluster_receiver
        ADMIN_PASSWORD: 123456
    command:
      - -f=/app/configs/config.toml
    depends_on:
      - mongodb
    restart: always