version: '3'
services:
  qelog_receiver:
     image: qelog:latest
     ports:
      - '31081:31081'
      - '31082:31082'
     volumes:
      - '/data/log/receiver:/app/receiver/log'
     entrypoint:
      - /app/receiver/qelog_receiver
      - -f=./configs/config.docker.toml
     restart: always

  qelog_admin:
    image: qelog:latest
    ports:
      - '31080:31080'
    volumes:
      - '/data/log/admin:/app/admin/log'
    entrypoint:
      - /app/admin/qelog_admin
      - -f=./configs/config.docker.toml
    depends_on:
      - qelog_receiver
    restart: always