version: '3'
services:
  qelog_receiver:
     image: qelog:latest
     ports:
      - '31081:31081'
      - '31082:31082'
     volumes:
      - '/data/log/receiver:/app/log'
     entrypoint:
      - /app/qelog_receiver
      - -f=configs/config.docker.toml
     restart: always

  qelog_manager:
    image: qelog:latest
    ports:
      - '31080:31080'
    volumes:
      - '/data/log/manager:/app/log'
    entrypoint:
      - /app/qelog_manager
      - -f=configs/config.docker.toml
    restart: always