# 运行环境
Env = "dev"

# 用于存储配置信息，统计信息等
[[Mongo.Conns]]
    Database = "qelog_admin"
    Uri = "mongodb://127.0.0.1:27017/admin"

# 用于存储日志信息
[[Mongo.Conns]]
    Database = "qelog_receiver_1"
    Uri = "mongodb://127.0.0.1:27017/admin"
# 用于存储日志信息
[[Mongo.Conns]]
    Database = "qelog_receiver_2"
    Uri = "mongodb://127.0.0.1:27017/admin"

[MongoGroup]
    AdminDatabase = "qelog_admin"
    ReceiverDatabase = ["qelog_receiver_1","qelog_receiver_2"]

# 管理后台
[Admin]
HttpListenAddr = "0.0.0.0:31080"
AuthEnable = true
Username = "admin"
Password = "111111"

# 日志接收
[Receiver]
HttpListenAddr = "0.0.0.0:31081"
RpcListenAddr = ":31082"
# 报警功能开启
AlarmEnable = true
# 统计信息开启
MetricsEnable = true

# 这里是接入Qelog 所需要的配置，Qelog管理后台接入了Qelog
[Logging]
# 模块名，相当于接入应用的身份标识
Module = "qelog"
# receiver的地址， GRPC 使用数组的方式支持轮询负载。 HTTP 建议直接配置域名+Nginx
Addr = ["127.0.0.1:31082"]
Filename = "./log/logger.log"