env = "dev"
receiverAddr = "0.0.0.0:31081"
receiverGRPCAddr = ":31082"
managerAddr = "0.0.0.0:31080"
alarmEnable = true
metricsEnable = true

[mongodb]
database = "qelog"
uri = "mongodb://127.0.0.1:27017/admin"