# 运行环境
env = "dev"
# Receiver 进程HTTP监听地址
receiverAddr = "0.0.0.0:31081"
# Receiver 进程GRPC监听地址
receiverGRPCAddr = ":31082"
# 管理后台进程HTTP监听地址
adminAddr = "0.0.0.0:31080"
# 管理后台权限验证开启
authEnable = true
# Receiver报警功能开启
alarmEnable = true
# Receiver 统计信息开启
metricsEnable = true
# Recerver 写入实例分片，可随时扩大
shardingIndexSize = 8
# Receiver 按天范围分集合
# 举例:7天为一个范围 则 1-7号 生成集合名为 logging_202002_1 8-14号 logging_202002_2
daySpan = 7
# 数据最大有效期 月
maxAgeMonth = 6

# 主库Mongodb，用于存储配置信息，统计信息等
#[main]
#database = "qelog"
#uri = "mongodb://127.0.0.1:27017/admin"

# Sharding 实例1。 这里的级别可自定义，可以是同Mongodb实例不同库，也可以不同实例
# index ShardingIndexSize 与此参数对应，可以理解成 redis 的db
# 实例配置就是, qelog 库负责，dbIndex 1,2,3,4 的存储
#[[sharding]]
#index = [1,2,3,4]
#database = "qelog"
#uri = "mongodb://127.0.0.1:27017/admin"
#
#[[sharding]]
#index = [5,6,7,8]
#database = "qelog2"
#uri = "mongodb://127.0.0.1:27017/admin"
[[Mongo.Conns]]
    Database = "qelog"
    Uri = "mongodb://127.0.0.1:27017/admin"

[[Mongo.Conns]]
    Database = "qelog1"
    Uri = "mongodb://127.0.0.1:27017/admin"
[[Mongo.Conns]]
    Database = "qelog2"
    Uri = "mongodb://127.0.0.1:27017/admin"

[MongoGroup]
    AdminDatabase = "qelog"
    ReceiverDatabase = ["qelog1","qelog2"]

# 管理后台登录密码
[AdminUser]
Username = "admin"
Password = "111111"

# 这里是接入Qelog 所需要的配置，Qelog管理后台接入了Qelog
[Logging]
# 模块名，相当于接入应用的身份标识
Module = "qelog"
# receiver的地址， GRPC 使用数组的方式支持轮询负载。 HTTP 建议直接配置域名+Nginx
Addr = []
Filename = "./log/logger.log"