env = "dev"
receiverAddr = "0.0.0.0:31081"
receiverGRPCAddr = ":31082"
managerAddr = "0.0.0.0:31080"
authEnable = false
alarmEnable = true
metricsEnable = true
maxShardingIndex = 8

[main]
database = "qelog"
uri = "mongodb://127.0.0.1:27017/admin"

[[sharding]]
index = [1,2,3,4]
database = "qelog"
uri = "mongodb://127.0.0.1:27017/admin"

[[sharding]]
index = [5,6,7,8]
database = "qelog2"
uri = "mongodb://127.0.0.1:27017/admin"


[adminUser]
username = "admin"
password = "111111"

[logging]
module = "qelog"
addr = ["127.0.0.1:31082"]