env = "dev"
receiverAddr = "0.0.0.0:31081"
receiverGRPCAddr = ":31082"
managerAddr = "0.0.0.0:31080"
authEnable = true
alarmEnable = true
metricsEnable = true
maxShardingIndex = 8
daySpan = 7

[main]
database = "qelog"
uri = "mongodb://root:111111@192.168.10.14:27017,192.168.10.14:27017/?replicaSet=fbj&authSource=admin"
#uri = "mongodb://host.docker.internal:27017/admin"

[[sharding]]
index = [1,2,3,4]
database = "qelog_sharding1"
uri = "mongodb://root:111111@192.168.10.14:27017,192.168.10.14:27017/?replicaSet=fbj&authSource=admin"

[[sharding]]
index = [5,6,7,8]
database = "qelog_sharding2"
uri = "mongodb://root:111111@mongodb1.dev.crycx.com:27017,mongodb2.dev.crycx.com:27017/?replicaSet=fbj&authSource=admin"



[adminUser]
username = "admin"
password = "111111"

[logging]
module = "qelog"
addr = ["192.168.10.114:31082"]